project:
  type: website
  output-dir: docs

website:
  title: "prostar-proteomics.org"
  favicon: "images/logo.png"
  site-url: "https://www.prostar-proteomics.org/"
  
  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: center
    search: true
    style: "docked"
    collapse-level: 0
    tools:
      - icon: github
        href: https://github.com/edyp-lab/Prostar
        text: "Prostar on GitHub"
        target: _blank
      - icon: code-square
        href: https://www.bioconductor.org/packages/release/bioc/html/Prostar.html
        text: "Prostar on Bioconductor"
        target: _blank
      - icon: globe
        href: https://www.edyp.fr/web/
        text: "EDyP Lab"
        target: _blank
        
    contents:
      - href: index.qmd
        text: Home
      - discoverprostar.qmd
      - download.qmd
      - releasenotes.qmd
      - section: ressources.qmd
        contents: 
          - faq.qmd
      - about.qmd

format:
  html:
    grid: 
      sidebar-width: 275px
      body-width: 1000px
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true
    page-layout: full
    code-copy: true
    code-overflow: wrap
    mainfont: Roboto

resources:
  - CNAME