project:
  type: website
  output-dir: docs

website:
  title: "prostar-proteomics.org"
  favicon: "images/logo.png"
  
  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: center
    search: true
    style: "docked"
    collapse-level: 0
    tools:
      - icon: github
        href: https://github.com/edyp-lab/Prostar2
        text: "Prostar on GitHub"
        
    contents:
      - href: index.qmd
        text: Home
      - discoverprostar.qmd
      - download.qmd
      - releasenotes.qmd
      - section: ressources.qmd
        contents: 
          - faq.qmd
      - about.qmd

format:
  html:
    grid: 
      sidebar-width: 275px
      body-width: 1000px
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true
    page-layout: full
    code-copy: true
    code-overflow: wrap
    mainfont: Roboto
