---
title: "Discover Prostar"
---

Prostar is a software tool dedicated to the differential analysis of quantitative data resulting from discovery proteomics experiments.

Prostar is easy to install (see our Zero-install page), easy to use (thanks to its Shiny-based click-button interface) and well-documented (see our reference page). Moreover, it has been regularly updated along years to provide state-of-the-art data science methodologies.

# Presentation
## Data management
- **Conversion**: To import a tabulated file containing quantitative data and convert it into an MSnset structure.
- **Loading**: To open an Msnset structure that has been previously constructed.
- **Exporting**: To save a partially/completely processed dataset and to download the data analysis results.
- **Demo data**: Toy datasets are available to discover Prostar potential in the simplest way.

## Data processing
- **Filtering**: To prune the protein or peptide list according to various criteria (missing values, string matching).
- **Normalization**: To correct batch or group effects.
- **Imputation**: By taking into account the very nature of each missing value.
- **Aggregation**: For peptide-level datasets, it is possible to estimate protein abundances.
- **Hypothesis testing**: To compute the significance of each protein differential abundance.

## Data mining
- **Descriptive statistics**: Available at any stage of the analysis, for data exploration and visualization.
- **Peptide-Protein Graph**: Explore and visualize peptide-protein graphs.
- **Differential analysis**: To select a list of differentially abundant proteins with a controlled false discovery rate.
- **Gene Ontology analysis**: To map a protein list onto GO terms and test category enrichment.


# Software
1. [**Zero-install**](#zero-install)  
The easiest way. Prostar is deployed as a zip archive (so far only available on Microsoft Windows desktop machines).
<!-- or as a Docker image (bêta, but ok for Windows, Mac OS X and (Unix/Linux). -->
2. [**Stand-alone Bioconductor install**](#bioconductor-installs)  
The standard method to install Bioconductor distributed software.
This method works for any operating systems (Unix/Linux, Mac OS X and Windows) 
as long as R is installed.
3. **Server install**  
When one wants Prostar to run on a Unix server, on which remote users connect.
This more advanced type of install is detailed in the [user manual](#useful-links).
<!-- 4. [**Online demo**](#online-demo)   -->
<!-- Before installing Prostar on your desktop machine, test our online demo! -->



